// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/relab/hotstuff/modules (interfaces: CliQueue)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	hotstuff "github.com/relab/hotstuff"
)

// MockCliQueue is a mock of CliQueue interface.
type MockCliQueue struct {
	ctrl     *gomock.Controller
	recorder *MockCliQueueMockRecorder
}

// MockCliQueueMockRecorder is the mock recorder for MockCliQueue.
type MockCliQueueMockRecorder struct {
	mock *MockCliQueue
}

// NewMockCliQueue creates a new mock instance.
func NewMockCliQueue(ctrl *gomock.Controller) *MockCliQueue {
	mock := &MockCliQueue{ctrl: ctrl}
	mock.recorder = &MockCliQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCliQueue) EXPECT() *MockCliQueueMockRecorder {
	return m.recorder
}

// AddTCSet mocks base method.
func (m *MockCliQueue) AddTCSet(arg0 hotstuff.TCSet) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddTCSet", arg0)
}

// AddTCSet indicates an expected call of AddTCSet.
func (mr *MockCliQueueMockRecorder) AddTCSet(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTCSet", reflect.TypeOf((*MockCliQueue)(nil).AddTCSet), arg0)
}
